version: '3.3'

services:
  passguardVault:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'passguard'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3306:3306
    volumes:
      - /vault:/var/lib/mysql